# Generated by Django 5.2.5 on 2025-11-04 04:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esim', '0018_sponsorad_button_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='GgselFailedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GgselFailedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GgselProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_goods', models.PositiveIntegerField(unique=True)),
                ('name_goods', models.CharField(max_length=512)),
                ('info_goods', models.TextField(blank=True, null=True)),
                ('add_info', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=10)),
                ('cnt_sell', models.IntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_rur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='GgselVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_value', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=500)),
                ('default', models.BooleanField(default=False)),
                ('modify', models.CharField(blank=True, max_length=50, null=True)),
                ('modify_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('modify_value_default', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('modify_type', models.CharField(blank=True, max_length=10, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('airalo_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ggsel_variants', to='esim.package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ggsel.ggselproduct')),
            ],
            options={
                'unique_together': {('product', 'variant_value')},
            },
        ),
        migrations.CreateModel(
            name='GgselOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(unique=True)),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('buyer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('buyer_payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_state', models.IntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField()),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('cart_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('is_my_product', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('invalid', 'Invalid / Skipped'), ('processing', 'Processing'), ('failed', 'Failed'), ('completed', 'Completed')], default='received', max_length=20)),
                ('ggsel_transaction_status', models.IntegerField(choices=[(1, 'Not Verified'), (2, 'Delivered'), (3, 'Delivery Confirmed'), (4, 'Refuted'), (5, 'Delivery Pending')], default=1)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('unique_code', models.CharField(blank=True, max_length=16, null=True)),
                ('order_info_received', models.BooleanField(default=False)),
                ('payment_verified', models.BooleanField(default=False)),
                ('task_enqueued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airalo_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ggsel_order', to='esim.airaloorder')),
                ('airalo_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ggsel_orders', to='esim.package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ggsel.ggselproduct')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ggsel.ggselvariant')),
            ],
            options={
                'verbose_name': 'Ggsel Order',
                'verbose_name_plural': 'Ggsel Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
