# Generated by Django 5.2.5 on 2025-11-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggsel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ggselfailedorder',
            name='unique_code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
