# Generated by Django 5.2.5 on 2025-11-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggsel', '0002_alter_ggselfailedorder_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ggselfailedorder',
            name='order_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
