# Generated by Django 5.2.3 on 2026-02-27 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0021_airalovoucherorder_airalovouchercode'),
        ('ggsel', '0003_ggselfailedorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ggselorder',
            name='voucher_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ggsel_order', to='esim.airalovoucherorder'),
        ),
    ]
