# Generated by Django 5.2.3 on 2026-04-18 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0024_digisellerorder_esim_email_sent'),
        ('ggsel', '0004_ggselorder_voucher_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ggselorder',
            name='esimaccess_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ggsel_order_ref', to='esim.esimaccessorder'),
        ),
    ]
