# Generated by Django 5.2.3 on 2026-04-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggsel', '0005_ggselorder_esimaccess_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ggselorder',
            name='esim_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
