# Generated by Django 5.2.3 on 2025-06-20 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiraloFailedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AiraloPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('raw_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AiraloToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('country_code', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DigisellerFailedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigisellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_goods', models.PositiveIntegerField(unique=True)),
                ('name_goods', models.CharField(max_length=512)),
                ('info_goods', models.TextField(blank=True, null=True)),
                ('add_info', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=10)),
                ('cnt_sell', models.IntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_rur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('user_type', models.IntegerField(choices=[(0, 'Admin'), (1, 'Staff')], default=2)),
                ('user_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Suspended')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('types', models.JSONField(blank=True, null=True)),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='esim.coverage')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.PositiveIntegerField()),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_prepaid', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('esim_type', models.CharField(blank=True, max_length=50, null=True)),
                ('apn_type', models.CharField(blank=True, max_length=50, null=True)),
                ('apn_value', models.CharField(blank=True, max_length=100, null=True)),
                ('is_roaming', models.BooleanField(default=False)),
                ('plan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('activation_policy', models.CharField(blank=True, max_length=50, null=True)),
                ('is_kyc_verify', models.BooleanField(default=False)),
                ('rechargeability', models.BooleanField(default=False)),
                ('other_info', models.TextField(blank=True, null=True)),
                ('info', models.JSONField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='esim.country')),
            ],
        ),
        migrations.AddField(
            model_name='coverage',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='esim.operator'),
        ),
        migrations.CreateModel(
            name='APN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ios_apn_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ios_apn_value', models.CharField(blank=True, max_length=100, null=True)),
                ('android_apn_type', models.CharField(blank=True, max_length=50, null=True)),
                ('android_apn_value', models.CharField(blank=True, max_length=100, null=True)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apn_config', to='esim.operator')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_countries', to='esim.operator')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('day', models.PositiveIntegerField(blank=True, null=True)),
                ('is_unlimited', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('short_info', models.TextField(blank=True, null=True)),
                ('qr_installation', models.TextField(blank=True, null=True)),
                ('manual_installation', models.TextField(blank=True, null=True)),
                ('is_fair_usage_policy', models.BooleanField(default=False)),
                ('fair_usage_policy', models.TextField(blank=True, null=True)),
                ('data', models.CharField(blank=True, max_length=50, null=True)),
                ('voice', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=50, null=True)),
                ('net_price', models.FloatField(blank=True, null=True)),
                ('prices', models.JSONField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='esim.operator')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('github_profile', models.URLField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DigisellerVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_value', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
                ('modify', models.CharField(blank=True, max_length=50, null=True)),
                ('modify_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('modify_value_default', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('modify_type', models.CharField(blank=True, max_length=10, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='esim.digisellerproduct')),
            ],
            options={
                'unique_together': {('product', 'variant_value')},
            },
        ),
    ]
