# Generated by Django 5.2.3 on 2025-06-20 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digisellervariant',
            name='airalo_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digiseller_variants', to='esim.package'),
        ),
    ]
