# Generated by Django 5.2.3 on 2025-06-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0002_digisellervariant_airalo_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
