# Generated by Django 5.2.3 on 2025-06-24 16:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0003_alter_package_package_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigisellerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(unique=True)),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('buyer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('buyer_payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_state', models.IntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField()),
                ('cart_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('is_my_product', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('invalid', 'Invalid / Skipped'), ('processing', 'Processing'), ('failed', 'Failed'), ('completed', 'Completed')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airalo_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='esim.package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='esim.digisellerproduct')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='esim.digisellervariant')),
            ],
            options={
                'verbose_name': 'Digiseller Order',
                'verbose_name_plural': 'Digiseller Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
