# Generated by Django 5.2.3 on 2025-06-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0004_digisellerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='digisellerorder',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
