# Generated by Django 5.2.3 on 2025-06-24 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0005_digisellerorder_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiraloOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airalo_id', models.PositiveIntegerField(unique=True)),
                ('code', models.CharField(max_length=32)),
                ('currency', models.CharField(max_length=8)),
                ('package_id', models.CharField(max_length=128)),
                ('quantity', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=255)),
                ('esim_type', models.CharField(blank=True, max_length=32, null=True)),
                ('validity', models.PositiveIntegerField(blank=True, null=True)),
                ('package_title', models.CharField(max_length=128)),
                ('data', models.CharField(blank=True, max_length=32, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at_api', models.DateTimeField()),
                ('manual_installation', models.TextField(blank=True, null=True)),
                ('qrcode_installation', models.TextField(blank=True, null=True)),
                ('installation_guides', models.JSONField(blank=True, null=True)),
                ('net_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='digisellerorder',
            name='airalo_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digiseller_order', to='esim.airaloorder'),
        ),
        migrations.CreateModel(
            name='AiraloSim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_id', models.PositiveIntegerField(unique=True)),
                ('iccid', models.CharField(max_length=22)),
                ('lpa', models.CharField(max_length=128)),
                ('qrcode', models.CharField(max_length=256)),
                ('qrcode_url', models.URLField()),
                ('direct_apple_installation_url', models.URLField(blank=True, null=True)),
                ('apn_type', models.CharField(blank=True, max_length=32, null=True)),
                ('apn_value', models.CharField(blank=True, max_length=64, null=True)),
                ('is_roaming', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('airalo_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sims', to='esim.airaloorder')),
            ],
        ),
    ]
