# Generated by Django 5.2.3 on 2025-06-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0007_digisellerorder_digiseller_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='digisellerorder',
            name='order_info_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='digisellerorder',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='digisellerorder',
            name='task_enqueued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='digisellerorder',
            name='unique_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='digisellervariant',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
