# Generated by Django 5.2.3 on 2025-07-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0008_digisellerorder_order_info_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigisellerFailedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
