# Generated by Django 5.2.3 on 2025-07-11 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0010_digisellerqueue_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='digisellerproduct',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='esim.market'),
        ),
    ]
