# Generated by Django 5.2.3 on 2025-07-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0011_digisellerproduct_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='region',
        ),
        migrations.AddField(
            model_name='market',
            name='market_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
