# Generated by Django 5.2.3 on 2025-07-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0012_remove_market_region_market_market_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='digisellerfailedorder',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
