# Generated by Django 5.2.3 on 2025-07-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0013_digisellerfailedorder_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airaloorder',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
