# Generated by Django 5.2.3 on 2025-08-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0015_purchasediscountad_selectedproductad_socialmediaad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='sponsor_ads/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
