# Generated by Django 5.2.3 on 2025-08-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0016_sponsorad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorad',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
