# Generated by Django 5.2.3 on 2025-08-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0017_sponsorad_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorad',
            name='button_label',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
