# Generated by Django 5.2.3 on 2026-02-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0018_sponsorad_button_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESIMAccessFailedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ESIMAccessPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('operator', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ESIMAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='provider',
            field=models.CharField(choices=[('airalo', 'Airalo'), ('esimaccess', 'ESIM Access')], db_index=True, default='airalo', max_length=20),
        ),
    ]
