# Generated by Django 5.2.3 on 2026-02-27 09:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0020_esimaccesswebhooklog_esimaccessorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiraloVoucherOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(db_index=True, max_length=64)),
                ('meta_message', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AiraloVoucherCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(db_index=True, max_length=128)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('booking_reference', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('voucher_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='esim.airalovoucherorder')),
            ],
            options={
                'unique_together': {('package_id', 'code', 'booking_reference')},
            },
        ),
    ]
