# Generated by Django 5.2.3 on 2026-02-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0021_airalovoucherorder_airalovouchercode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AiraloPackage',
        ),
    ]
