# Generated by Django 5.2.3 on 2026-03-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0022_delete_airalopackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiraloPackage',
            fields=[
            ],
            options={
                'verbose_name': 'Airalo Package',
                'verbose_name_plural': 'Airalo Packages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('esim.package',),
        ),
        migrations.CreateModel(
            name='SmartEsimPackage',
            fields=[
            ],
            options={
                'verbose_name': 'Smart eSIM',
                'verbose_name_plural': 'Smart eSIMs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('esim.package',),
        ),
        migrations.AddField(
            model_name='esimaccesssim',
            name='installation_guides',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
