# Generated by Django 5.2.3 on 2026-03-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0023_airalopackage_smartesimpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digisellerorder',
            name='esim_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
