# Generated by Django 5.2.3 on 2026-04-20 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0024_digisellerorder_esim_email_sent'),
        ('ggsel', '0006_ggselorder_esim_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='esimaccessfailedorder',
            name='ggsel_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esimaccess_failures', to='ggsel.ggselorder'),
        ),
    ]
