# Generated by Django 5.2.3 on 2026-04-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esim', '0025_esimaccessfailedorder_ggsel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='digisellerorder',
            name='buyer_payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='digisellerorder',
            name='purchase_currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operatorcountry',
            name='country_code',
            field=models.CharField(max_length=10),
        ),
    ]
